# Environment
TASK: "DOMESTIC_BRA"
DATA_PATH: "/data/brazil"
MODEL_PATH: "models_saved/best_gat.pth"

# Model Architecture
SPATIAL_CONTEXT: 12
ENCODER_FEATURES: [32, 64]
ENCODER_OUTPUT: 256
GAT_HEADS: 4
GAT_OUTPUT_FEATURES_PER_HEAD: 64
HIDDEN_DIM: 256

# Regularization & Training
SPATIAL_REFINER_DROPOUT: 0.3
REGRESSOR_DROPOUT: 0.3
EPOCHS: 201
LEARNING_RATE_GAT: 0.0005
LEARNING_RATE_ALPHA: 0.01